[package]
name = "final-spv-circuit"
version = "0.1.0"
edition = "2021"

[build-dependencies]
risc0-build = { version = "2.1.1" }
risc0-binfmt = {version = "2.0.1"}

[package.metadata.risc0]
methods = ["guest"]
